import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateCoreSchema1783865000000 implements MigrationInterface {
  name = 'CreateCoreSchema1783865000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const statements = [
      `CREATE TABLE IF NOT EXISTS members (
        id INT NOT NULL AUTO_INCREMENT,
        npk VARCHAR(10) NOT NULL,
        name VARCHAR(100) NOT NULL,
        email VARCHAR(100) NULL,
        workUnit VARCHAR(50) NULL,
        phone VARCHAR(20) NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'active',
        organizationalPosition VARCHAR(100) NULL,
        plant VARCHAR(10) NULL,
        distributionAreaId INT NULL,
        createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        deletedAt DATETIME(6) NULL,
        PRIMARY KEY (id),
        UNIQUE KEY UQ_members_npk (npk),
        KEY IDX_members_status (status),
        KEY IDX_members_plant_work_unit (plant, workUnit)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS users (
        id INT NOT NULL AUTO_INCREMENT,
        npk VARCHAR(10) NOT NULL,
        password VARCHAR(255) NOT NULL,
        mustChangePassword TINYINT NOT NULL DEFAULT 0,
        isActive TINYINT NOT NULL DEFAULT 1,
        failedLoginAttempts INT NOT NULL DEFAULT 0,
        lockedUntil DATETIME NULL,
        lastLoginAt DATETIME NULL,
        memberId INT NULL,
        createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        UNIQUE KEY UQ_users_npk (npk),
        UNIQUE KEY UQ_users_member (memberId),
        CONSTRAINT FK_users_member FOREIGN KEY (memberId) REFERENCES members(id) ON DELETE SET NULL
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS audit_logs (
        id INT NOT NULL AUTO_INCREMENT,
        userId INT NULL,
        action VARCHAR(100) NOT NULL,
        module VARCHAR(50) NOT NULL,
        entityType VARCHAR(50) NULL,
        entityId INT NULL,
        oldValues JSON NULL,
        newValues JSON NULL,
        ipAddress VARCHAR(45) NULL,
        userAgent VARCHAR(255) NULL,
        description VARCHAR(255) NULL,
        createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        KEY IDX_audit_module_action_created (module, action, createdAt),
        KEY IDX_audit_user_created (userId, createdAt)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS login_histories (
        id INT NOT NULL AUTO_INCREMENT,
        userId INT NOT NULL,
        ipAddress VARCHAR(45) NULL,
        userAgent VARCHAR(255) NULL,
        isSuccess TINYINT NOT NULL DEFAULT 0,
        failureReason VARCHAR(255) NULL,
        createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        KEY IDX_login_user_created (userId, createdAt),
        CONSTRAINT FK_login_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS sessions (
        id INT NOT NULL AUTO_INCREMENT,
        userId INT NOT NULL,
        refreshToken VARCHAR(500) NOT NULL,
        ipAddress VARCHAR(45) NULL,
        userAgent VARCHAR(255) NULL,
        expiresAt DATETIME NOT NULL,
        isActive TINYINT NOT NULL DEFAULT 1,
        createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        UNIQUE KEY UQ_sessions_refresh_token (refreshToken),
        KEY IDX_sessions_user_active (userId, isActive),
        CONSTRAINT FK_sessions_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS password_reset_tokens (
        id INT NOT NULL AUTO_INCREMENT,
        userId INT NOT NULL,
        token VARCHAR(255) NOT NULL,
        expiresAt DATETIME NOT NULL,
        isUsed TINYINT NOT NULL DEFAULT 0,
        createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        UNIQUE KEY UQ_password_reset_token (token),
        KEY IDX_password_reset_user (userId, isUsed, expiresAt),
        CONSTRAINT FK_password_reset_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS permissions (
        id INT NOT NULL AUTO_INCREMENT,
        name VARCHAR(100) NOT NULL,
        \`group\` VARCHAR(50) NOT NULL,
        description VARCHAR(255) NULL,
        createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        UNIQUE KEY UQ_permissions_name (name),
        KEY IDX_permissions_group (\`group\`)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS roles (
        id INT NOT NULL AUTO_INCREMENT,
        name VARCHAR(50) NOT NULL,
        description VARCHAR(255) NULL,
        isSystem TINYINT NOT NULL DEFAULT 0,
        createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        UNIQUE KEY UQ_roles_name (name)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS role_permissions (
        roleId INT NOT NULL,
        permissionId INT NOT NULL,
        PRIMARY KEY (roleId, permissionId),
        CONSTRAINT FK_role_permissions_role FOREIGN KEY (roleId) REFERENCES roles(id) ON DELETE CASCADE,
        CONSTRAINT FK_role_permissions_permission FOREIGN KEY (permissionId) REFERENCES permissions(id) ON DELETE CASCADE
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS user_roles (
        id INT NOT NULL AUTO_INCREMENT,
        userId INT NOT NULL,
        roleId INT NOT NULL,
        areaId INT NULL,
        assignedBy INT NULL,
        assignedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        startsAt DATETIME NULL,
        endsAt DATETIME NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
        revokedAt DATETIME NULL,
        revokedBy INT NULL,
        reason VARCHAR(255) NULL,
        PRIMARY KEY (id),
        KEY IDX_user_roles_active (userId, status, revokedAt, startsAt, endsAt),
        KEY IDX_user_roles_role_area (roleId, areaId, revokedAt),
        CONSTRAINT FK_user_roles_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT FK_user_roles_role FOREIGN KEY (roleId) REFERENCES roles(id) ON DELETE CASCADE
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS user_role_histories (
        id INT NOT NULL AUTO_INCREMENT,
        userId INT NOT NULL,
        roleId INT NOT NULL,
        areaId INT NULL,
        startsAt DATETIME NULL,
        endsAt DATETIME NULL,
        status VARCHAR(20) NOT NULL,
        action ENUM('ASSIGN','REVOKE') NOT NULL,
        changedBy INT NOT NULL,
        reason VARCHAR(255) NULL,
        createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        KEY IDX_user_role_history_user (userId, createdAt),
        CONSTRAINT FK_user_role_history_user FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
        CONSTRAINT FK_user_role_history_role FOREIGN KEY (roleId) REFERENCES roles(id) ON DELETE CASCADE
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS member_status_histories (
        id INT NOT NULL AUTO_INCREMENT,
        memberId INT NOT NULL,
        oldStatus VARCHAR(20) NOT NULL,
        newStatus VARCHAR(20) NOT NULL,
        reason VARCHAR(255) NULL,
        changedByUserId INT NULL,
        createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        KEY IDX_member_status_history_member (memberId, createdAt),
        CONSTRAINT FK_member_status_history_member FOREIGN KEY (memberId) REFERENCES members(id) ON DELETE CASCADE
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS bazaar_events (
        id INT NOT NULL AUTO_INCREMENT,
        code VARCHAR(30) NOT NULL,
        name VARCHAR(255) NOT NULL,
        description TEXT NULL,
        banner_image_url VARCHAR(500) NULL,
        subsidy DECIMAL(12,2) NOT NULL DEFAULT 20000,
        goodie_bag_fee DECIMAL(12,2) NOT NULL DEFAULT 3000,
        application_fee DECIMAL(12,2) NOT NULL DEFAULT 1000,
        isActive TINYINT NOT NULL DEFAULT 1,
        created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        deleted_at DATETIME(6) NULL,
        PRIMARY KEY (id),
        UNIQUE KEY UQ_bazaar_events_code (code),
        KEY IDX_bazaar_events_active (isActive, deleted_at)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS bazaar_batches (
        id INT NOT NULL AUTO_INCREMENT,
        event_id INT NOT NULL,
        name VARCHAR(255) NOT NULL,
        description TEXT NULL,
        purchase_start_at TIMESTAMP NULL,
        purchase_end_at TIMESTAMP NULL,
        distribution_start_at TIMESTAMP NULL,
        distribution_end_at TIMESTAMP NULL,
        status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
        is_purchase_enabled TINYINT NOT NULL DEFAULT 0,
        display_next_batch_information TINYINT NOT NULL DEFAULT 0,
        created_by INT NULL,
        updated_by INT NULL,
        created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        deleted_at DATETIME(6) NULL,
        PRIMARY KEY (id),
        KEY IDX_bazaar_batches_event_status (event_id, status, deleted_at),
        CONSTRAINT FK_bazaar_batches_event FOREIGN KEY (event_id) REFERENCES bazaar_events(id) ON DELETE CASCADE
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS bazaar_products (
        id INT NOT NULL AUTO_INCREMENT,
        event_id INT NOT NULL,
        name VARCHAR(255) NOT NULL,
        slug VARCHAR(255) NOT NULL,
        sku VARCHAR(50) NULL,
        description TEXT NULL,
        normal_price DECIMAL(10,2) NOT NULL DEFAULT 0,
        selling_price DECIMAL(10,2) NOT NULL DEFAULT 0,
        image_url VARCHAR(500) NULL,
        maximum_quantity_per_member INT NOT NULL DEFAULT 1,
        inventory_mode VARCHAR(50) NOT NULL DEFAULT 'UNLIMITED',
        stock INT NOT NULL DEFAULT 0,
        is_active TINYINT NOT NULL DEFAULT 1,
        display_order INT NOT NULL DEFAULT 0,
        created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        deleted_at DATETIME(6) NULL,
        PRIMARY KEY (id),
        UNIQUE KEY UQ_bazaar_products_slug (slug),
        KEY IDX_bazaar_products_event_active (event_id, is_active, deleted_at),
        CONSTRAINT FK_bazaar_products_event FOREIGN KEY (event_id) REFERENCES bazaar_events(id) ON DELETE CASCADE
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS distribution_areas (
        id INT NOT NULL AUTO_INCREMENT,
        code VARCHAR(50) NOT NULL,
        name VARCHAR(255) NOT NULL,
        description TEXT NULL,
        is_active TINYINT NOT NULL DEFAULT 1,
        created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        deleted_at DATETIME(6) NULL,
        PRIMARY KEY (id),
        UNIQUE KEY UQ_distribution_areas_code (code)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS organizational_unit_area_mappings (
        id INT NOT NULL AUTO_INCREMENT,
        plant VARCHAR(100) NOT NULL,
        work_unit VARCHAR(100) NOT NULL,
        distribution_area_id INT NOT NULL,
        is_active TINYINT NOT NULL DEFAULT 1,
        created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        deleted_at DATETIME(6) NULL,
        PRIMARY KEY (id),
        UNIQUE KEY UQ_area_mapping (plant, work_unit, deleted_at),
        KEY IDX_area_mapping_lookup (plant, work_unit, is_active),
        CONSTRAINT FK_area_mapping_area FOREIGN KEY (distribution_area_id) REFERENCES distribution_areas(id) ON DELETE CASCADE
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS bazaar_orders (
        id INT NOT NULL AUTO_INCREMENT,
        order_number VARCHAR(40) NOT NULL,
        user_id INT NOT NULL,
        event_id INT NOT NULL,
        batch_id INT NOT NULL,
        status ENUM('PENDING','CONFIRMED','PAID','CANCELLED','EXPIRED','COMPLETED') NOT NULL DEFAULT 'PENDING',
        productSubtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
        goodieBagFee DECIMAL(12,2) NOT NULL DEFAULT 0,
        applicationFee DECIMAL(12,2) NOT NULL DEFAULT 0,
        subsidy DECIMAL(12,2) NOT NULL DEFAULT 0,
        grandTotal DECIMAL(12,2) NOT NULL DEFAULT 0,
        distribution_area_id INT NULL,
        terms_accepted TINYINT NOT NULL DEFAULT 0,
        terms_version VARCHAR(20) NULL,
        terms_accepted_at TIMESTAMP NULL,
        cancel_reason TEXT NULL,
        pending_purchase_key VARCHAR(64)
          GENERATED ALWAYS AS (
            CASE WHEN status = 'PENDING' THEN CONCAT(user_id, ':', event_id) ELSE NULL END
          ) STORED,
        successful_purchase_key VARCHAR(64)
          GENERATED ALWAYS AS (
            CASE WHEN status IN ('CONFIRMED','PAID','COMPLETED') THEN CONCAT(user_id, ':', event_id) ELSE NULL END
          ) STORED,
        created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        deleted_at DATETIME(6) NULL,
        PRIMARY KEY (id),
        UNIQUE KEY UQ_orders_number (order_number),
        UNIQUE KEY UQ_orders_pending_purchase (pending_purchase_key),
        UNIQUE KEY UQ_orders_successful_purchase (successful_purchase_key),
        KEY IDX_orders_user_event_status (user_id, event_id, status),
        KEY IDX_orders_batch_status (batch_id, status),
        CONSTRAINT FK_orders_user FOREIGN KEY (user_id) REFERENCES users(id),
        CONSTRAINT FK_orders_event FOREIGN KEY (event_id) REFERENCES bazaar_events(id),
        CONSTRAINT FK_orders_batch FOREIGN KEY (batch_id) REFERENCES bazaar_batches(id),
        CONSTRAINT FK_orders_distribution_area FOREIGN KEY (distribution_area_id) REFERENCES distribution_areas(id)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS order_sequences (
        event_id INT NOT NULL,
        batch_id INT NOT NULL,
        sequence_year INT NOT NULL,
        next_value BIGINT NOT NULL DEFAULT 0,
        PRIMARY KEY (event_id, batch_id, sequence_year),
        CONSTRAINT FK_order_sequences_event FOREIGN KEY (event_id) REFERENCES bazaar_events(id),
        CONSTRAINT FK_order_sequences_batch FOREIGN KEY (batch_id) REFERENCES bazaar_batches(id)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS bazaar_order_items (
        id INT NOT NULL AUTO_INCREMENT,
        order_id INT NOT NULL,
        product_id INT NOT NULL,
        product_name_snapshot VARCHAR(255) NOT NULL,
        product_price_snapshot DECIMAL(12,2) NOT NULL,
        quantity INT NOT NULL DEFAULT 1,
        subtotal DECIMAL(12,2) NOT NULL,
        created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        UNIQUE KEY UQ_order_item_product (order_id, product_id),
        CONSTRAINT FK_order_items_order FOREIGN KEY (order_id) REFERENCES bazaar_orders(id) ON DELETE CASCADE,
        CONSTRAINT FK_order_items_product FOREIGN KEY (product_id) REFERENCES bazaar_products(id)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS bazaar_order_status_histories (
        id INT NOT NULL AUTO_INCREMENT,
        order_id INT NOT NULL,
        status VARCHAR(20) NOT NULL,
        notes TEXT NULL,
        created_by VARCHAR(255) NULL,
        created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        KEY IDX_order_history_order (order_id, created_at),
        CONSTRAINT FK_order_history_order FOREIGN KEY (order_id) REFERENCES bazaar_orders(id) ON DELETE CASCADE
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS payments (
        id INT NOT NULL AUTO_INCREMENT,
        order_id INT NOT NULL,
        reference_id VARCHAR(255) NOT NULL,
        provider VARCHAR(50) NOT NULL,
        provider_reference VARCHAR(255) NULL,
        amount DECIMAL(12,2) NOT NULL,
        status ENUM('UNPAID','PENDING','PAID','EXPIRED','FAILED','MANUAL_VERIFIED','REFUNDED') NOT NULL DEFAULT 'UNPAID',
        qris_payload TEXT NULL,
        expired_at TIMESTAMP NULL,
        paid_at TIMESTAMP NULL,
        created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        UNIQUE KEY UQ_payments_reference (reference_id),
        UNIQUE KEY UQ_payments_order (order_id),
        KEY IDX_payments_status_expired (status, expired_at),
        CONSTRAINT FK_payments_order FOREIGN KEY (order_id) REFERENCES bazaar_orders(id)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS payment_webhook_logs (
        id INT NOT NULL AUTO_INCREMENT,
        provider VARCHAR(50) NOT NULL,
        eventType VARCHAR(100) NULL,
        externalReference VARCHAR(255) NULL,
        payload JSON NOT NULL,
        signatureValid TINYINT NOT NULL DEFAULT 0,
        processingStatus VARCHAR(30) NOT NULL,
        errorMessage VARCHAR(500) NULL,
        receivedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        processedAt DATETIME NULL,
        PRIMARY KEY (id),
        KEY IDX_webhook_reference (provider, externalReference),
        KEY IDX_webhook_received (receivedAt)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS manual_payment_verifications (
        id INT NOT NULL AUTO_INCREMENT,
        paymentId INT NOT NULL,
        verifiedBy INT NOT NULL,
        previousStatus VARCHAR(30) NOT NULL,
        newStatus VARCHAR(30) NOT NULL,
        amount DECIMAL(12,2) NOT NULL,
        paymentReference VARCHAR(255) NOT NULL,
        reason VARCHAR(500) NOT NULL,
        notes TEXT NULL,
        createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        KEY IDX_manual_payment (paymentId, createdAt),
        CONSTRAINT FK_manual_payment FOREIGN KEY (paymentId) REFERENCES payments(id),
        CONSTRAINT FK_manual_verified_by FOREIGN KEY (verifiedBy) REFERENCES users(id)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS payment_status_histories (
        id INT NOT NULL AUTO_INCREMENT,
        payment_id INT NOT NULL,
        status ENUM('UNPAID','PENDING','PAID','EXPIRED','FAILED','MANUAL_VERIFIED','REFUNDED') NOT NULL,
        notes TEXT NULL,
        created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        KEY IDX_payment_history_payment (payment_id, created_at),
        CONSTRAINT FK_payment_history_payment FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS pickup_tokens (
        id INT NOT NULL AUTO_INCREMENT,
        order_id INT NOT NULL,
        token_code VARCHAR(255) NOT NULL,
        is_used TINYINT NOT NULL DEFAULT 0,
        created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        UNIQUE KEY UQ_pickup_tokens_order (order_id),
        UNIQUE KEY UQ_pickup_tokens_code (token_code),
        CONSTRAINT FK_pickup_tokens_order FOREIGN KEY (order_id) REFERENCES bazaar_orders(id)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS distributions (
        id INT NOT NULL AUTO_INCREMENT,
        order_id INT NOT NULL,
        distributed_by INT NOT NULL,
        notes TEXT NULL,
        distributed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        UNIQUE KEY UQ_distributions_order (order_id),
        KEY IDX_distributions_pic_date (distributed_by, distributed_at),
        CONSTRAINT FK_distributions_order FOREIGN KEY (order_id) REFERENCES bazaar_orders(id),
        CONSTRAINT FK_distributions_user FOREIGN KEY (distributed_by) REFERENCES users(id)
      ) ENGINE=InnoDB`,
      `CREATE TABLE IF NOT EXISTS distribution_histories (
        id INT NOT NULL AUTO_INCREMENT,
        distributionId INT NOT NULL,
        orderId INT NOT NULL,
        performedBy INT NOT NULL,
        action VARCHAR(50) NOT NULL,
        notes TEXT NULL,
        createdAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
        PRIMARY KEY (id),
        KEY IDX_distribution_history_order (orderId, createdAt),
        CONSTRAINT FK_distribution_history_distribution FOREIGN KEY (distributionId) REFERENCES distributions(id),
        CONSTRAINT FK_distribution_history_order FOREIGN KEY (orderId) REFERENCES bazaar_orders(id),
        CONSTRAINT FK_distribution_history_user FOREIGN KEY (performedBy) REFERENCES users(id)
      ) ENGINE=InnoDB`,
    ];

    for (const statement of statements) {
      await queryRunner.query(statement);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const tables = [
      'distribution_histories',
      'distributions',
      'pickup_tokens',
      'payment_status_histories',
      'manual_payment_verifications',
      'payment_webhook_logs',
      'payments',
      'bazaar_order_status_histories',
      'bazaar_order_items',
      'bazaar_orders',
      'order_sequences',
      'organizational_unit_area_mappings',
      'distribution_areas',
      'bazaar_products',
      'bazaar_batches',
      'bazaar_events',
      'member_status_histories',
      'user_role_histories',
      'user_roles',
      'role_permissions',
      'roles',
      'permissions',
      'password_reset_tokens',
      'sessions',
      'login_histories',
      'audit_logs',
      'users',
      'members',
    ];

    for (const table of tables) {
      await queryRunner.query(`DROP TABLE IF EXISTS \`${table}\``);
    }
  }
}
